CREATE TABLE [dbo].[ADMINISTRADORES] (
    [numeroIdentidad] VARCHAR (13)  NOT NULL,
    [contrasena]      NVARCHAR (80) NOT NULL,
    CONSTRAINT [PK_ADMINISTRADORES] PRIMARY KEY CLUSTERED ([numeroIdentidad] ASC),
    CONSTRAINT [FK_ADMINISTRADORES_PERSONAL] FOREIGN KEY ([numeroIdentidad]) REFERENCES [dbo].[PERSONAL] ([numeroIdentidad]) ON DELETE CASCADE ON UPDATE CASCADE
);

